apiVersion: v1
kind: Service
metadata:
  name: geo-processor
  namespace: geoint
spec:
  selector:
    app: geo-processor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP