apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-ingest
  namespace: geoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-ingest
  template:
    metadata:
      labels:
        app: geo-ingest
    spec:
      initContainers:
        - name: wait-for-postgis
          image: postgres:15
          command: ['sh', '-c', 'until pg_isready -h postgis -p 5432; do sleep 2; done;']
      containers:
        - name: geo-ingest
          image: geo-ingest:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgis
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: geoint-db
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password