apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-processor
  namespace: geoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-processor
  template:
    metadata:
      labels:
        app: geo-processor
    spec:
      initContainers:
        - name: wait-for-postgis
          image: postgres:15
          command: ['sh', '-c', 'until pg_isready -h postgis -p 5432; do sleep 2; done;']
      containers:
        - name: geo-processor
          image: geo-processor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000 # - Port that FastAPI will listen on
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgis-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgis-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgis-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: POSTGRES_PASSWORD
              