apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
  namespace: geoint
spec:
  serviceName: postgis
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - name: postgis
          image: postgis/postgis:15-3.3
          ports: 
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: geoint-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
